### ISSUE TITLE
Linux builds failing for  2.6.9

### ISSUE THREAD

**Issue by robbmcleod** [MacPython/numexpr-wheels#2]
Looks like the Linux wheels are failing due to a missing SSL certificate at:

https://nipy.bic.berkeley.edu/manylinux

**Comment by matthew-brett** [comment]
Have you updated multibuild recently?  The nipy server got retired a while ago, from multibuild.

**Comment by robbmcleod** [comment]
No, I hadn't. So I've updated it now. I just found the discussion from September.

**Comment by robbmcleod** [comment]
Ok that's one down, thanks.
